---
- name: Set plugin instance's configuration instance ({{instance.alias}} {{instance.version}})
  set_fact:
    config: '{{instance | dict2items | rejectattr("key", "in", ["version", "alias"]) | list | items2dict | combine({"version": 1})}}'

- name: Configure plugin instance ({{instance.alias}} {{instance.version}})
  copy: dest=/etc/netappdvp/{{instance.alias}}_{{instance.version}}.json content='{{config | to_nice_json}}' mode=0600 owner=root group=root
  register: trident__r_config

- name: Find all installed docker plugins
  command: docker plugin ls --format {% raw %}'{{.Name}}'{% endraw %}
  check_mode: no
  changed_when: no
  register: trident__r_plugins_installed

- name: Install plugin instance ({{instance.alias}} {{instance.version}})
  command: docker plugin install --grant-all-permissions --alias {{instance.alias}}:{{instance.version}} netapp/trident-plugin:{{instance.version}} config=/etc/netappdvp/{{instance.alias}}_{{instance.version}}.json
  when: "(instance.alias + ':' + instance.version) not in trident__r_plugins_installed.stdout_lines"
  register: trident__r_install

- name: Restart plugin instance ({{instance.alias}} {{instance.version}})
  shell: >-
    docker plugin disable {{instance.alias}}:{{instance.version}} &&
    docker plugin enable {{instance.alias}}:{{instance.version}}
  when: trident__r_config.changed or trident__r_install.changed
