---
- name: Install nfs-utils
  yum: name=nfs-utils state=present

- name: Enable RPCBind
  service: name=rpcbind state=started enabled=true

- name: Create directory for trident config
  file: path=/etc/netappdvp/ state=directory

- name: Configure trident
  template: dest=/etc/netappdvp/config.json src=config.json.j2 mode=0644 owner=root group=root
  notify: "Restart netapp plugin"

- name: Install trident
  command: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:19.07 config=/etc/netappdvp/config.json
  register: trident__r_install_plugin
  changed_when: "'already exists' not in trident__r_install_plugin.stderr"
  failed_when:
    - "not ('Installed plugin netapp/trident-plugin:19.07' in trident__r_install_plugin.stdout)"
    - "not ('plugin netapp:latest already exists' in trident__r_install_plugin.stderr)"
