---
- name: Install nfs-utils
  yum: name=nfs-utils state=present

- name: Enable RPCBind
  service: name=rpcbind state=started enabled=true

- name: Create directory for trident config
  file: path=/etc/netappdvp/ state=directory

- name: Configure trident
  template: dest=/etc/netappdvp/config.json src=config.json.j2 mode=0644 owner=root group=root

- name: Check if trident pluging is downloaded
  shell: docker plugin ls | grep netapp
  register: trident__r_plugin_exists
  ignore_errors: yes

- name: Install trident
  shell: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:19.07 config=/etc/netappdvp/config.json
  when: trident__r_plugin_exists.rc == 1

