---
- name: Create directory for trident config
  file: path=/etc/netappdvp/ state=directory

- name: Configure trident
  template: dest=/etc/netappdvp/config.json src=config.json.j2 mode=0644 owner=root group=root
  notify: "Restart netapp plugin"

- name: Find all installed docker plugins
  command: docker plugin ls --format {% raw %}'{{.Name}}'{% endraw %}
  check_mode: no
  changed_when: no
  register: trident__r_plugins_installed

- name: Install trident
  command: docker plugin install --disable --grant-all-permissions --alias netapp:{{trident_version}} netapp/trident-plugin:{{trident_version}} config=/etc/netappdvp/config.json
  when: "'netapp:' + trident_version not in trident__r_plugins_installed.stdout_lines"

- name: Find enabled docker plugins
  command: docker plugin ls -f enabled=true --format {% raw %}'{{.Name}}'{% endraw %}
  check_mode: no
  changed_when: no
  register: trident__r_plugins_enabled

- name: Disable other versions of the docker plugin
  command: docker plugin disable {{item}}
  loop: '{{trident__r_plugins_enabled.stdout_lines}}'
  when:
    - item | regex_replace('^(.*):.*$', '\\1') == 'netapp'
    - item != 'netapp:' + trident_version

- name: Ensure correct version in enabled
  command: docker plugin enable netapp:{{trident_version}}
  when: "'netapp:' + trident_version not in trident__r_plugins_enabled.stdout_lines"
