---
- name: Disable netapp plugin
  command: docker plugin disable netapp:{{trident_version}}
  listen: "Restart netapp plugin"

- name: Enable netapp plugin
  command: docker plugin enable netapp:{{trident_version}}
  listen: "Restart netapp plugin"
